workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Apideck:
        inputs:
            - location: ../unify/speakeasy-spec.yml
        registry:
            location: registry.speakeasyapi.dev/apideck-k2o/apideck/apideck
targets:
    apideck:
        target: php
        source: Apideck
        publish:
            packagist:
                username: Apideck
                token: $packagist_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/apideck-k2o/apideck/apideck-php-code-samples
            blocking: false
