<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Operations;

use Apideck\Unify\Models\Components;
class AccountingDepartmentsDeleteResponse
{
    /**
     *
     * @var \Apideck\Unify\Models\Components\HTTPMetadata $httpMeta
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?Components\HTTPMetadata $httpMeta;

    /**
     * Department deleted
     *
     * @var ?\Apideck\Unify\Models\Components\DeleteAccountingDepartmentResponse $deleteAccountingDepartmentResponse
     */
    public ?Components\DeleteAccountingDepartmentResponse $deleteAccountingDepartmentResponse = null;

    /**
     * Unexpected error
     *
     * @var ?\Apideck\Unify\Models\Components\UnexpectedErrorResponse $unexpectedErrorResponse
     */
    public ?Components\UnexpectedErrorResponse $unexpectedErrorResponse = null;

    /**
     * @param  \Apideck\Unify\Models\Components\HTTPMetadata  $httpMeta
     * @param  ?\Apideck\Unify\Models\Components\DeleteAccountingDepartmentResponse  $deleteAccountingDepartmentResponse
     * @param  ?\Apideck\Unify\Models\Components\UnexpectedErrorResponse  $unexpectedErrorResponse
     * @phpstan-pure
     */
    public function __construct(Components\HTTPMetadata $httpMeta, ?Components\DeleteAccountingDepartmentResponse $deleteAccountingDepartmentResponse = null, ?Components\UnexpectedErrorResponse $unexpectedErrorResponse = null)
    {
        $this->httpMeta = $httpMeta;
        $this->deleteAccountingDepartmentResponse = $deleteAccountingDepartmentResponse;
        $this->unexpectedErrorResponse = $unexpectedErrorResponse;
    }
}