<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Operations;

use Apideck\Unify\Models\Components;
class AccountingAgedCreditorsOneResponse
{
    /**
     *
     * @var \Apideck\Unify\Models\Components\HTTPMetadata $httpMeta
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?Components\HTTPMetadata $httpMeta;

    /**
     * Aged Creditors
     *
     * @var ?\Apideck\Unify\Models\Components\GetAgedCreditorsResponse $getAgedCreditorsResponse
     */
    public ?Components\GetAgedCreditorsResponse $getAgedCreditorsResponse = null;

    /**
     * Unexpected error
     *
     * @var ?\Apideck\Unify\Models\Components\UnexpectedErrorResponse $unexpectedErrorResponse
     */
    public ?Components\UnexpectedErrorResponse $unexpectedErrorResponse = null;

    /**
     * @param  \Apideck\Unify\Models\Components\HTTPMetadata  $httpMeta
     * @param  ?\Apideck\Unify\Models\Components\GetAgedCreditorsResponse  $getAgedCreditorsResponse
     * @param  ?\Apideck\Unify\Models\Components\UnexpectedErrorResponse  $unexpectedErrorResponse
     * @phpstan-pure
     */
    public function __construct(Components\HTTPMetadata $httpMeta, ?Components\GetAgedCreditorsResponse $getAgedCreditorsResponse = null, ?Components\UnexpectedErrorResponse $unexpectedErrorResponse = null)
    {
        $this->httpMeta = $httpMeta;
        $this->getAgedCreditorsResponse = $getAgedCreditorsResponse;
        $this->unexpectedErrorResponse = $unexpectedErrorResponse;
    }
}