<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Operations;

use Apideck\Unify\Models\Components;
class AccountingBillsDeleteResponse
{
    /**
     *
     * @var \Apideck\Unify\Models\Components\HTTPMetadata $httpMeta
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?Components\HTTPMetadata $httpMeta;

    /**
     * Bill deleted
     *
     * @var ?\Apideck\Unify\Models\Components\DeleteBillResponse $deleteBillResponse
     */
    public ?Components\DeleteBillResponse $deleteBillResponse = null;

    /**
     * Unexpected error
     *
     * @var ?\Apideck\Unify\Models\Components\UnexpectedErrorResponse $unexpectedErrorResponse
     */
    public ?Components\UnexpectedErrorResponse $unexpectedErrorResponse = null;

    /**
     * @param  \Apideck\Unify\Models\Components\HTTPMetadata  $httpMeta
     * @param  ?\Apideck\Unify\Models\Components\DeleteBillResponse  $deleteBillResponse
     * @param  ?\Apideck\Unify\Models\Components\UnexpectedErrorResponse  $unexpectedErrorResponse
     * @phpstan-pure
     */
    public function __construct(Components\HTTPMetadata $httpMeta, ?Components\DeleteBillResponse $deleteBillResponse = null, ?Components\UnexpectedErrorResponse $unexpectedErrorResponse = null)
    {
        $this->httpMeta = $httpMeta;
        $this->deleteBillResponse = $deleteBillResponse;
        $this->unexpectedErrorResponse = $unexpectedErrorResponse;
    }
}