<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Operations;


class VaultConnectionsTokenRequestBody
{

    public function __construct()
    {
    }
}