<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Operations;

use Apideck\Unify\Models\Components;
class VaultConsumersAllResponse
{
    /**
     *
     * @var \Apideck\Unify\Models\Components\HTTPMetadata $httpMeta
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?Components\HTTPMetadata $httpMeta;

    /**
     * Consumers
     *
     * @var ?\Apideck\Unify\Models\Components\GetConsumersResponse $getConsumersResponse
     */
    public ?Components\GetConsumersResponse $getConsumersResponse = null;

    /**
     * Unexpected error
     *
     * @var ?\Apideck\Unify\Models\Components\UnexpectedErrorResponse $unexpectedErrorResponse
     */
    public ?Components\UnexpectedErrorResponse $unexpectedErrorResponse = null;

    /**
     * @var \Closure(string): ?VaultConsumersAllResponse $next
     */
    public \Closure $next;
    /**
     * @param  \Apideck\Unify\Models\Components\HTTPMetadata  $httpMeta
     * @param  ?\Apideck\Unify\Models\Components\GetConsumersResponse  $getConsumersResponse
     * @param  ?\Apideck\Unify\Models\Components\UnexpectedErrorResponse  $unexpectedErrorResponse
     * @phpstan-pure
     */
    public function __construct(Components\HTTPMetadata $httpMeta, ?Components\GetConsumersResponse $getConsumersResponse = null, ?Components\UnexpectedErrorResponse $unexpectedErrorResponse = null)
    {
        $this->httpMeta = $httpMeta;
        $this->getConsumersResponse = $getConsumersResponse;
        $this->unexpectedErrorResponse = $unexpectedErrorResponse;
    }
    /**
     * @param  string  $name
     * @param  array<mixed>  $args
     * @return ?VaultConsumersAllResponse
     */
    public function __call($name, $args): ?VaultConsumersAllResponse
    {
        if ($name === 'next') {
            return call_user_func_array($this->next, $args);
        }

        return null;
    }
}