<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Components;

use Apideck\Unify\Utils\SpeakeasyMetadata;
class BankAccountFilter
{
    /**
     * Filter by account type
     *
     * @var ?BankAccountFilterAccountType $accountType
     */
    #[SpeakeasyMetadata('queryParam:name=account_type')]
    public ?BankAccountFilterAccountType $accountType = null;

    /**
     * @param  ?BankAccountFilterAccountType  $accountType
     * @phpstan-pure
     */
    public function __construct(?BankAccountFilterAccountType $accountType = null)
    {
        $this->accountType = $accountType;
    }
}