<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Components;


class CustomField1
{
    /**
     * Unique identifier for the custom field.
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public ?string $id;

    /**
     * Name of the custom field.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * More information about the custom field
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     *
     * @var string|float|bool|array<string, mixed>|array<string|float|bool|array<string, mixed>|null>|null $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|array<string, mixed>|array<string|float|bool|array<string, mixed>|null>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|array|null $value = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $name
     * @param  ?string  $description
     * @param  string|float|bool|array<string, mixed>|array<string|float|bool|array<string, mixed>|null>|null  $value
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $name = null, ?string $description = null, string|float|bool|array|null $value = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->description = $description;
        $this->value = $value;
    }
}