<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Components;


class Defaults
{
    /**
     *
     * @var ?Target $target
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('target')]
    #[\Speakeasy\Serializer\Annotation\Type('\Apideck\Unify\Models\Components\Target|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Target $target = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * $options
     *
     * @var ?array<SimpleFormFieldOption|FormFieldOptionGroup> $options
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('options')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Apideck\Unify\Models\Components\SimpleFormFieldOption|\Apideck\Unify\Models\Components\FormFieldOptionGroup>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $options = null;

    /**
     *
     * @var string|int|float|bool|array<string|int|float>|null $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|int|float|bool|array<string|int|float>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|int|float|bool|array|null $value = null;

    /**
     * @param  ?Target  $target
     * @param  ?string  $id
     * @param  ?array<SimpleFormFieldOption|FormFieldOptionGroup>  $options
     * @param  string|int|float|bool|array<string|int|float>|null  $value
     */
    public function __construct(?Target $target = null, ?string $id = null, ?array $options = null, string|int|float|bool|array|null $value = null)
    {
        $this->target = $target;
        $this->id = $id;
        $this->options = $options;
        $this->value = $value;
    }
}