<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Components;


class EnvironmentNotes
{
    /**
     * Environment name.
     *
     * @var string $environment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('environment')]
    public string $environment;

    /**
     * Description of the environment.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * @param  string  $environment
     * @param  string  $description
     * @phpstan-pure
     */
    public function __construct(string $environment, string $description)
    {
        $this->environment = $environment;
        $this->description = $description;
    }
}