<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Components;


class FilesSearch
{
    /**
     * The query to search for. May match across multiple fields.
     *
     * @var string $query
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('query')]
    public string $query;

    /**
     * ID of the drive to filter on
     *
     * @var ?string $driveId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('drive_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $driveId = null;

    /**
     * The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.
     *
     * @var ?array<PassThroughBody> $passThrough
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pass_through')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Apideck\Unify\Models\Components\PassThroughBody>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $passThrough = null;

    /**
     * @param  string  $query
     * @param  ?string  $driveId
     * @param  ?array<PassThroughBody>  $passThrough
     */
    public function __construct(string $query, ?string $driveId = null, ?array $passThrough = null)
    {
        $this->query = $query;
        $this->driveId = $driveId;
        $this->passThrough = $passThrough;
    }
}