<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Components;


class JournalInput
{
    /**
     * Code used to select this journal when posting entries. For Exact Online, pass this code as journal_symbol, not the journal id.
     *
     * @var ?string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $code = null;

    /**
     * Name of the journal.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * Description of the journal.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Normalized journal classification.
     *
     * @var ?\Apideck\Unify\Models\Components\JournalType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Apideck\Unify\Models\Components\JournalType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?JournalType $type = null;

    /**
     * Whether the journal permits VAT on entries. Null or absent means unknown. Exact Online exposes this setting for general journals; it must not be treated as a universal VAT capability flag for other journal types.
     *
     * @var ?bool $allowVat
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allow_vat')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowVat = null;

    /**
     * Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
     *
     * @var ?\Apideck\Unify\Models\Components\Currency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\Apideck\Unify\Models\Components\Currency|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Currency $currency = null;

    /**
     * International Bank Account Number
     *
     * @var ?string $iban
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('iban')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $iban = null;

    /**
     * A flexible account reference that can represent a ledger account (GL account), a bank account, or an employee payable account, depending on the connector's requirements.
     *
     * @var ?\Apideck\Unify\Models\Components\LinkedFinancialAccountInput $defaultAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('default_account')]
    #[\Speakeasy\Serializer\Annotation\Type('\Apideck\Unify\Models\Components\LinkedFinancialAccountInput|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LinkedFinancialAccountInput $defaultAccount = null;

    /**
     * Whether the journal is blocked for posting.
     *
     * @var ?bool $blocked
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('blocked')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $blocked = null;

    /**
     * @param  ?string  $code
     * @param  ?string  $name
     * @param  ?string  $description
     * @param  ?\Apideck\Unify\Models\Components\JournalType  $type
     * @param  ?bool  $allowVat
     * @param  ?\Apideck\Unify\Models\Components\Currency  $currency
     * @param  ?string  $iban
     * @param  ?\Apideck\Unify\Models\Components\LinkedFinancialAccountInput  $defaultAccount
     * @param  ?bool  $blocked
     * @phpstan-pure
     */
    public function __construct(?string $code = null, ?string $name = null, ?string $description = null, ?JournalType $type = null, ?bool $allowVat = null, ?Currency $currency = null, ?string $iban = null, ?LinkedFinancialAccountInput $defaultAccount = null, ?bool $blocked = null)
    {
        $this->code = $code;
        $this->name = $name;
        $this->description = $description;
        $this->type = $type;
        $this->allowVat = $allowVat;
        $this->currency = $currency;
        $this->iban = $iban;
        $this->defaultAccount = $defaultAccount;
        $this->blocked = $blocked;
    }
}