<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Components;


class LinkedTaxRateInput
{
    /**
     * $additionalProperties
     *
     * @var ?array<string, mixed> $additionalProperties
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('additionalProperties')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $additionalProperties = null;

    /**
     * The ID of the object.
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Tax rate code
     *
     * @var ?string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $code = null;

    /**
     * Rate of the tax rate
     *
     * @var ?float $rate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $rate = null;

    /**
     * @param  ?array<string, mixed>  $additionalProperties
     * @param  ?string  $id
     * @param  ?string  $code
     * @param  ?float  $rate
     * @phpstan-pure
     */
    public function __construct(?array $additionalProperties = null, ?string $id = null, ?string $code = null, ?float $rate = null)
    {
        $this->additionalProperties = $additionalProperties;
        $this->id = $id;
        $this->code = $code;
        $this->rate = $rate;
    }
}