<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Components;


/** Meta - Response metadata */
class Meta
{
    /**
     * Number of items returned in the data property of the response
     *
     * @var ?int $itemsOnPage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items_on_page')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $itemsOnPage = null;

    /**
     * Cursors to navigate to previous or next pages through the API
     *
     * @var ?\Apideck\Unify\Models\Components\Cursors $cursors
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cursors')]
    #[\Speakeasy\Serializer\Annotation\Type('\Apideck\Unify\Models\Components\Cursors|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Cursors $cursors = null;

    /**
     * Number of records available in total for this resource
     *
     * @var ?int $totalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_count')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $totalCount = null;

    /**
     * @param  ?int  $itemsOnPage
     * @param  ?\Apideck\Unify\Models\Components\Cursors  $cursors
     * @param  ?int  $totalCount
     * @phpstan-pure
     */
    public function __construct(?int $itemsOnPage = null, ?Cursors $cursors = null, ?int $totalCount = null)
    {
        $this->itemsOnPage = $itemsOnPage;
        $this->cursors = $cursors;
        $this->totalCount = $totalCount;
    }
}