<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Components;

use Apideck\Unify\Utils\SpeakeasyMetadata;
class OpportunitiesSort
{
    /**
     * The field on which to sort the Opportunities
     *
     * @var ?\Apideck\Unify\Models\Components\OpportunitiesSortBy $by
     */
    #[SpeakeasyMetadata('queryParam:name=by')]
    public ?OpportunitiesSortBy $by = null;

    /**
     * The direction in which to sort the results
     *
     * @var ?\Apideck\Unify\Models\Components\SortDirection $direction
     */
    #[SpeakeasyMetadata('queryParam:name=direction')]
    public ?SortDirection $direction = null;

    /**
     * @param  ?\Apideck\Unify\Models\Components\OpportunitiesSortBy  $by
     * @param  ?\Apideck\Unify\Models\Components\SortDirection  $direction
     * @phpstan-pure
     */
    public function __construct(?OpportunitiesSortBy $by = null, ?SortDirection $direction = SortDirection::Asc)
    {
        $this->by = $by;
        $this->direction = $direction;
    }
}