<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify\Models\Components;

use Brick\DateTime\LocalDate;
class Quote
{
    /**
     * A unique identifier for an object.
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * The unique identifier for the invoice.
     *
     * @var ?string $invoiceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoice_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $invoiceId = null;

    /**
     * The unique identifier for the linked project.
     *
     * @var ?string $projectId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('project_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $projectId = null;

    /**
     * $lineItems
     *
     * @var ?array<QuoteLineItem> $lineItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('line_items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Apideck\Unify\Models\Components\QuoteLineItem>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $lineItems = null;

    /**
     *
     * @var ?Address $billingAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Apideck\Unify\Models\Components\Address|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Address $billingAddress = null;

    /**
     *
     * @var ?Address $shippingAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('shipping_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Apideck\Unify\Models\Components\Address|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Address $shippingAddress = null;

    /**
     * $customFields
     *
     * @var ?array<CustomField> $customFields
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('custom_fields')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Apideck\Unify\Models\Components\CustomField>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $customFields = null;

    /**
     * The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.
     *
     * @var ?array<PassThroughBody> $passThrough
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pass_through')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Apideck\Unify\Models\Components\PassThroughBody>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $passThrough = null;

    /**
     * The third-party API ID of original entity
     *
     * @var ?string $downstreamId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('downstream_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $downstreamId = null;

    /**
     * Quote number.
     *
     * @var ?string $number
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $number = null;

    /**
     * The customer this entity is linked to.
     *
     * @var ?LinkedCustomer $customer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer')]
    #[\Speakeasy\Serializer\Annotation\Type('\Apideck\Unify\Models\Components\LinkedCustomer|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LinkedCustomer $customer = null;

    /**
     * The unique identifier for the sales order.
     *
     * @var ?string $salesOrderId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sales_order_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $salesOrderId = null;

    /**
     * The company or subsidiary id the transaction belongs to
     *
     * @var ?string $companyId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('company_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $companyId = null;

    /**
     * Date quote was issued - YYYY-MM-DD.
     *
     * @var ?LocalDate $quoteDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quote_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $quoteDate = null;

    /**
     * The date until which the quote is valid - YYYY-MM-DD.
     *
     * @var ?LocalDate $expiryDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expiry_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $expiryDate = null;

    /**
     * Terms of the quote.
     *
     * @var ?string $terms
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('terms')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $terms = null;

    /**
     * Optional reference identifier for the transaction.
     *
     * @var ?string $reference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $reference = null;

    /**
     * Quote status
     *
     * @var ?QuoteStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Apideck\Unify\Models\Components\QuoteStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?QuoteStatus $status = null;

    /**
     * Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
     *
     * @var ?Currency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\Apideck\Unify\Models\Components\Currency|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Currency $currency = null;

    /**
     * Currency Exchange Rate at the time entity was recorded/generated.
     *
     * @var ?float $currencyRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency_rate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $currencyRate = null;

    /**
     * Amounts are including tax
     *
     * @var ?bool $taxInclusive
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_inclusive')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $taxInclusive = null;

    /**
     * Sub-total amount, normally before tax.
     *
     * @var ?float $subTotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sub_total')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $subTotal = null;

    /**
     * Total tax amount applied to this quote.
     *
     * @var ?float $totalTax
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_tax')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $totalTax = null;

    /**
     * Applicable tax id/code override if tax is not supplied on a line item basis.
     *
     * @var ?string $taxCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxCode = null;

    /**
     * Discount percentage applied to this quote.
     *
     * @var ?float $discountPercentage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount_percentage')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $discountPercentage = null;

    /**
     * Discount amount applied to this quote.
     *
     * @var ?float $discountAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $discountAmount = null;

    /**
     * Total amount of quote, including tax.
     *
     * @var ?float $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $total = null;

    /**
     * Customer memo
     *
     * @var ?string $customerMemo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_memo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerMemo = null;

    /**
     * A list of linked tracking categories.
     *
     * @var ?array<?LinkedTrackingCategory> $trackingCategories
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tracking_categories')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Apideck\Unify\Models\Components\LinkedTrackingCategory|null>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $trackingCategories = null;

    /**
     * Optional quote template
     *
     * @var ?string $templateId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('template_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $templateId = null;

    /**
     * URL link to a source document - shown as 'Go to [appName]' in the downstream app.
     *
     * @var ?string $sourceDocumentUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_document_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sourceDocumentUrl = null;

    /**
     * A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.
     *
     * @var ?string $rowVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('row_version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $rowVersion = null;

    /**
     * The user who last updated the object.
     *
     * @var ?string $updatedBy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_by')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $updatedBy = null;

    /**
     * The user who created the object.
     *
     * @var ?string $createdBy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_by')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $createdBy = null;

    /**
     * The date and time when the object was last updated.
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * The date and time when the object was created.
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $invoiceId
     * @param  ?string  $projectId
     * @param  ?array<QuoteLineItem>  $lineItems
     * @param  ?Address  $billingAddress
     * @param  ?Address  $shippingAddress
     * @param  ?array<CustomField>  $customFields
     * @param  ?array<PassThroughBody>  $passThrough
     * @param  ?string  $downstreamId
     * @param  ?string  $number
     * @param  ?LinkedCustomer  $customer
     * @param  ?string  $salesOrderId
     * @param  ?string  $companyId
     * @param  ?LocalDate  $quoteDate
     * @param  ?LocalDate  $expiryDate
     * @param  ?string  $terms
     * @param  ?string  $reference
     * @param  ?QuoteStatus  $status
     * @param  ?Currency  $currency
     * @param  ?float  $currencyRate
     * @param  ?bool  $taxInclusive
     * @param  ?float  $subTotal
     * @param  ?float  $totalTax
     * @param  ?string  $taxCode
     * @param  ?float  $discountPercentage
     * @param  ?float  $discountAmount
     * @param  ?float  $total
     * @param  ?string  $customerMemo
     * @param  ?array<?LinkedTrackingCategory>  $trackingCategories
     * @param  ?string  $templateId
     * @param  ?string  $sourceDocumentUrl
     * @param  ?string  $rowVersion
     * @param  ?string  $updatedBy
     * @param  ?string  $createdBy
     * @param  ?\DateTime  $updatedAt
     * @param  ?\DateTime  $createdAt
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $invoiceId = null, ?string $projectId = null, ?array $lineItems = null, ?Address $billingAddress = null, ?Address $shippingAddress = null, ?array $customFields = null, ?array $passThrough = null, ?string $downstreamId = null, ?string $number = null, ?LinkedCustomer $customer = null, ?string $salesOrderId = null, ?string $companyId = null, ?LocalDate $quoteDate = null, ?LocalDate $expiryDate = null, ?string $terms = null, ?string $reference = null, ?QuoteStatus $status = null, ?Currency $currency = null, ?float $currencyRate = null, ?bool $taxInclusive = null, ?float $subTotal = null, ?float $totalTax = null, ?string $taxCode = null, ?float $discountPercentage = null, ?float $discountAmount = null, ?float $total = null, ?string $customerMemo = null, ?array $trackingCategories = null, ?string $templateId = null, ?string $sourceDocumentUrl = null, ?string $rowVersion = null, ?string $updatedBy = null, ?string $createdBy = null, ?\DateTime $updatedAt = null, ?\DateTime $createdAt = null)
    {
        $this->id = $id;
        $this->invoiceId = $invoiceId;
        $this->projectId = $projectId;
        $this->lineItems = $lineItems;
        $this->billingAddress = $billingAddress;
        $this->shippingAddress = $shippingAddress;
        $this->customFields = $customFields;
        $this->passThrough = $passThrough;
        $this->downstreamId = $downstreamId;
        $this->number = $number;
        $this->customer = $customer;
        $this->salesOrderId = $salesOrderId;
        $this->companyId = $companyId;
        $this->quoteDate = $quoteDate;
        $this->expiryDate = $expiryDate;
        $this->terms = $terms;
        $this->reference = $reference;
        $this->status = $status;
        $this->currency = $currency;
        $this->currencyRate = $currencyRate;
        $this->taxInclusive = $taxInclusive;
        $this->subTotal = $subTotal;
        $this->totalTax = $totalTax;
        $this->taxCode = $taxCode;
        $this->discountPercentage = $discountPercentage;
        $this->discountAmount = $discountAmount;
        $this->total = $total;
        $this->customerMemo = $customerMemo;
        $this->trackingCategories = $trackingCategories;
        $this->templateId = $templateId;
        $this->sourceDocumentUrl = $sourceDocumentUrl;
        $this->rowVersion = $rowVersion;
        $this->updatedBy = $updatedBy;
        $this->createdBy = $createdBy;
        $this->updatedAt = $updatedAt;
        $this->createdAt = $createdAt;
    }
}