<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Apideck\Unify;

use Apideck\Unify\Utils\Retry;

/**
 * ApideckBuilder is used to configure and build an instance of the SDK.
 */
class ApideckBuilder
{
    public function __construct(
        private SDKConfiguration $sdkConfig = new SDKConfiguration(),
    ) {
    }

    /**
     * setClient allows setting a custom Guzzle client for the SDK to make requests with.
     *
     * @param  \GuzzleHttp\ClientInterface  $client
     * @return ApideckBuilder
     */
    public function setClient(\GuzzleHttp\ClientInterface $client): ApideckBuilder
    {
        $this->sdkConfig->client = $client;

        return $this;
    }

    /**
     * setSecurity is used to configure the security required for the SDK.
     *
     * @param  string  $apiKey
     * @return ApideckBuilder
     */
    public function setSecurity(string $apiKey): ApideckBuilder
    {
        $security = new Models\Components\Security(
            apiKey: $apiKey
        );
        $this->sdkConfig->securitySource = fn () => $security;

        return $this;
    }

    /**
     * setSecuritySource is usd to configure the security required for the SDK.
     * unlike setSecurity, setSecuritySource accepts a closure that will be called to retrieve the security information.
     *
     * @param  pure-Closure(): string  $securitySource
     * @return ApideckBuilder
     */
    public function setSecuritySource(\Closure $securitySource): ApideckBuilder
    {
        $this->sdkConfig->securitySource = fn () => new Models\Components\Security(apiKey: $securitySource());

        return $this;
    }

    /**
     * setServerUrl is used to configure the server URL for the SDK, and optionally template any parameters in the URL.
     *
     * @param  string  $serverUrl
     * @param  array<string, string>  $params
     * @return ApideckBuilder
     */
    public function setServerUrl(string $serverUrl, ?array $params = null): ApideckBuilder
    {
        $this->sdkConfig->serverUrl = Utils\Utils::templateUrl($serverUrl, $params);

        return $this;
    }

    /**
     * setServer is used to configure the server for the SDK
     *
     * @param  int  $serverIdx
     * @return ApideckBuilder
     */
    public function setServerIndex(int $serverIdx): ApideckBuilder
    {
        $this->sdkConfig->serverIndex = $serverIdx;

        return $this;
    }
    /**
     * setConsumerId is used to configure the consumerId parameter for the SDK.
     *
     * @param  string  $consumerId
     * @return ApideckBuilder
     */
    public function setConsumerId(string $consumerId): ApideckBuilder
    {
        if (! array_key_exists('header', $this->sdkConfig->globals['parameters'])) {
            $this->sdkConfig->globals['parameters']['header'] = [];
        }

        $this->sdkConfig->globals['parameters']['header']['consumerId'] = $consumerId;

        return $this;
    }
    /**
     * setAppId is used to configure the appId parameter for the SDK.
     *
     * @param  string  $appId
     * @return ApideckBuilder
     */
    public function setAppId(string $appId): ApideckBuilder
    {
        if (! array_key_exists('header', $this->sdkConfig->globals['parameters'])) {
            $this->sdkConfig->globals['parameters']['header'] = [];
        }

        $this->sdkConfig->globals['parameters']['header']['appId'] = $appId;

        return $this;
    }

    public function setRetryConfig(Retry\RetryConfig $config): ApideckBuilder
    {
        $this->sdkConfig->retryConfig = $config;

        return $this;
    }

    /**
     * build is used to build the SDK with any of the configured options.
     *
     * @return Apideck
     */
    public function build(): Apideck
    {
        if ($this->sdkConfig->client === null) {
            $this->sdkConfig->client = new \GuzzleHttp\Client([
                'timeout' => 60,
            ]);
        }
        if ($this->sdkConfig->hasSecurity()) {
            $this->sdkConfig->client = Utils\Utils::configureSecurityClient($this->sdkConfig->client, $this->sdkConfig->getSecurity());
        }

        return new Apideck($this->sdkConfig);
    }
}